project_id = "tnosyowzngwbwgmxtioh"

[functions.chat]
verify_jwt = false

[functions.generate-resume]
verify_jwt = false

[functions.parse-resume]
verify_jwt = false

[functions.scrape-job-description]
verify_jwt = false