// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnosyowzngwbwgmxtioh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRub3N5b3d6bmd3YndnbXh0aW9oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5ODc5OTksImV4cCI6MjA4ODU2Mzk5OX0.CWzyA2V1jM9eSfpbxxW1PoZpLCwisK-NXnT1N88FTJI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});